[workspace]
resolver = "3"
members = [
    "packages/analytics",
    "packages/user-management",
]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
serde = "1.0.219"
# Shared dependencies can be defined here
