[package]
name = "karya-user-management"
version = "0.1.0"
edition = "2024"

[dependencies]
# Error
derive_more = "2"

# Web framework
axum = "0.8"

# logging & Tracing
axum-tracing-opentelemetry = "0.28"
axum-otel-metrics = "0.10"
tracing = "0.1"
init-tracing-opentelemetry = { version = "0.28", features = ["tracing_subscriber_ext"] }

# Database
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "macros", "chrono", "uuid"] }
tokio = { version = "1.44", features = ["full"] }

# Serialization/Deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Time handling
chrono = { version = "0.4", features = ["serde"] }